# Site settings
title: Nathan's Blog
email: nathan.daniel.robinson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog about my interests, views and experiences.  This is also the
  Blog for my grade 10 personal project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nrobinson2000
github_username:  nrobinson2000
particle_username: nrobinson2000

# Build settings
kramdown:
  input: GFM
