# Site settings
title: Nathan's Blog
email: nathan.daniel.robinson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog about my interests, views and experiences.  This is also the
  Blog for my grade 10 personal project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nrobinson2000
github_username:  nrobinson2000
particle_username: nrobinson2000

nav_message: >
  <h3>About my Blog:</h3>
  <p>This blog is hosted on GitHub pages on my GitHub account.  You can see the <a href src="https://github.com/nrobinson2000/nrobinson2000.github.io">source code here.</a><p>
  <br>
  <p>This blog is powered by <a href src="https://jekyllrb.com">Jekyll</a>.  Jekyll is an automatic blog / website generator that compiles GitHub flavored markdown into HTML
  files.</p>





# Build settings
kramdown:
  input: GFM
